apiVersion: batch/v1
kind: Job
metadata:
  name: runner-experiment
spec:
  template:
    metadata:
      labels:
        app: gmini
    spec:
      containers:
      - name: runner
        image: sugiyat/gmini-runner:latest
        command: []
        env:
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_PASSWORD
      restartPolicy: Never
  backoffLimit: 4
  ttlSecondsAfterFinished: 60