apiVersion: v1
kind: Service
metadata:
  name: gmini-backend
  namespace: default
  labels:
    app: gmini
spec:
  selector:
    app: gmini
    tier: backend
  ports:
    - protocol: TCP
      port: # port of your choice ie 8080
      targetPort: # port of your choice ie 8080