apiVersion: v1
kind: Service
metadata:
  name: gmini-frontend
  namespace: default
  labels:
    app: gmini
spec:
  selector:
    app: gmini
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer