apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
  labels:
    app: gmini
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  hostPath:
    path: "/data/mongo"