apiVersion: v1
kind: Service
metadata:
  name: gmini-mongodb
  namespace: default
  labels:
    app: gmini
spec:
  selector:
    app: gmini
    tier: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017